server:
  port: 8080
spring:
  datasource:
    url:  jdbc:postgresql://ec2-34-231-63-30.compute-1.amazonaws.com/d84akn0tht1rpv?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: oqnzosdwphclfq
    password: 6d4c5d824316c2de1e23ae594ea7df946678a7cf515302471a2863fce5867a88
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: kocho703shinobu@gmail.com
    password: on3Punchm4n
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false